### ISSUE TITLE
Incompatible with malilib-fabric-1.18.1-0.11.4

### ISSUE THREAD

**Issue by mmodrow** [vacla/MobCountMod#4]
As I already mentioned on CurseForge.com, masady / @maruohon brought out a new version of maruohon/malilib@525b8940642c50d98d2a274ce7049529476d61f1 (malilib-fabric-1.18.1-0.11.4), which is mandatory for the current version of his mods (e.g. the only official release of MiniHUD for 1.18 - maruohon/minihud@fd4548c6ca14f4d408eeed17a25f9e52b22712af) and that is incompatible with your mod.

I'd greatly appreciate you looking into this, so both MobCountMod & MiniHUD can be run in parallel on 1.18

Log from the crash: 
```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058 (C:\Games\Minecraft\fabric-loader-1.18.1\mods\mobcountmod-fabric-1.18.0-1.8.20211206.220058.jar) with any version that is compatible with:
		 - malilib 0.11.4
Unmet dependency listing:
	 - Mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058 requires any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive) of mod 'MaLiLib' (malilib), but only the wrong version is present: 0.11.4!
		 - Mod 'MaLiLib' (malilib) 0.11.4 is being loaded from C:\Games\Minecraft\fabric-loader-1.18.1\mods\malilib-fabric-1.18.1-0.11.4.jar
Inactive mods:
	 - mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058 (C:\Games\Minecraft\fabric-loader-1.18.1\mods\mobcountmod-fabric-1.18.0-1.8.20211206.220058.jar) with any version that is compatible with:
		 - malilib 0.11.4
Unmet dependency listing:
	 - Mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058 requires any version between 0.10.0-dev.26 (inclusive) and 0.11 (exclusive) of mod 'MaLiLib' (malilib), but only the wrong version is present: 0.11.4!
		 - Mod 'MaLiLib' (malilib) 0.11.4 is being loaded from C:\Games\Minecraft\fabric-loader-1.18.1\mods\malilib-fabric-1.18.1-0.11.4.jar
Inactive mods:
	 - mod 'MobCountMod' (mobcountmod) 1.8.20211206.220058, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446388, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.8+a00e834b88, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.4+cbda931888, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
```

**Comment by vacla** [comment]
I will see if im able to do it this weekend or not, i might not need to do a lot of changes

**Comment by vacla** [comment]
Just noting here also, i will be updating this after i get my new pc
